#!/bin/sh

[ ! "${DMENU_OSX_CACHE_DIR}" ] &&
    echo "You must set the DMENU_OSX_CACHE_DIR env var" &&
    exit 1


[ ! -d "${DMENU_OSX_CACHE_DIR}" ] &&
    mkdir "${DMENU_OSX_CACHE_DIR}"

infile="${DMENU_OSX_CACHE_DIR}/input"
outfile="${DMENU_OSX_CACHE_DIR}/output"

touch "${infile}" "${outfile}"
cat /dev/stdin > "${infile}"

popup-term "<${infile} fzf > ${outfile}"

cat "${outfile}" && exit 0
