#!/bin/sh

[ ! "$HISTFILE" ] &&
    echo "HISTFILE is not set" &&
    exit 1

hist_dir=$(dirname "$HISTFILE")
hist_bak="${hist_dir}/histfile.bak"

cat "$HISTFILE" >> "$hist_bak"
cp "$hist_bak" "$HISTFILE"

echo "histfile:     $(wc -l "$HISTFILE")"
echo "histfile.bak: $(wc -l "$hist_bak")"
echo "DONE"
