#!/bin/bash

remote=()

while IFS= read -r line; do
    trimmed=$( echo "$line" | tr -d '[:space:]' )
    remote+=( "$trimmed" )
done < <( git branch --remotes )

index=1

for branch in "${remote[@]}"; do
    echo "$index" "$branch"
    ((index++))
done

echo "Which remote branch do you want to link locally?"
read -r num
index=$((num-1))
branch=${remote[$index]}
branch=$(echo "$branch" | sed 's/origin\///')

git checkout -b "$branch"
git branch --set-upstream-to=origin/"$branch" "$branch"

