#!/bin/sh

CMD="$EDITOR "

if [ -d $HOME/.Profigs ]; then
	ALLFILES=$({ find $HOME/.Profigs -type f | grep -v '.git'; 2>/dev/null find $HOME/* -type f; echo "$HOME/.histfile"; })
else
	ALLFILES=$({ 2>/dev/null find $HOME/* -type f; echo "$HOME/.histfile"; })
fi

FILES=$(echo "$ALLFILES" | fzf -m | tr '\n' ' ' | sed 's/ $//')

[ -z "$FILES" ] && exit 1

CMD+=$FILES

echo "$CMD" >> $HOME/.histfile

eval $CMD
