#!/bin/sh

# This script is called by i3 on startup

# Increase key speed via a rate change
xset r rate 300 50

# Map the caps lock key to super
setxkbmap -option caps:super

# When pressed once, treat super as escape
killall xcape ; xcape -e 'Super_L=Escape'

# Map the menu button to right super
xmodmap -e 'keycode 135 = Super_R'
