#!/bin/sh

# This script is called by i3 on startup

# Increase key speed via a rate change
xset r rate 300 50

# Use the caps lock key as super
setxkbmap -option caps:super

# When pressed once, treat super as escape
killall xcape ; xcape -e 'Super_L=Escape'

# Use the menu button as right super
xmodmap -e 'keycode 135 = Super_R'

# Use f10 key as cap locks
xmodmap -e 'add lock = F10'
