#!/bin/bash

OLD=$HOME/.cache/profigs/$(date +%m-%d-%Y_Time%H-%M-%S)
mkdir -p "$OLD"

OLD_CONF=$OLD/.config
CONF=$HOME/.config
P_HOME=$HOME/.Profigs/home
P_CONF=$HOME/.Profigs/config

lsim() {
    find "$1" -maxdepth 1 -mindepth 1 -exec basename {} \;
}

home_links_to() {
    find "$HOME" -maxdepth 1 -type l -ls | grep -q "$1 \-> $2/$1"
}

for FILE in $(lsim "$P_HOME"); do
    if ! home_links_to "$FILE" "$P_HOME"; then
        mv "$HOME/$FILE" "$OLD"
        ln -s "$P_HOME/$FILE" "$HOME"
    fi
done

if ! home_links_to "$CONF" "$P_CONF"; then
    mv "$CONF" "$OLD"
    ln -s "$P_CONF" "$CONF"
    for FILE in $(lsim "$OLD/.config"); do
        mv -n "$OLD_CONF/$FILE" "$CONF"
    done
fi

