#!/bin/sh

case $BLOCK_BUTTON in
	1) setsid "$TERMINAL" -e pulsemixer & ;;
	3) pulsemixer --toggle-mute ;;
	4) pulsemixer --change-volume +10 ;;
	5) pulsemixer --change-volume -10 ;;
esac

[ "$(pulsemixer --get-mute)" = "1" ] && printf "\\n" && exit

vol=$(pulsemixer --get-volume | awk '{print $1}')

if [ "$vol" -gt "50" ]
then
	icon=""
else
	icon=""
fi

printf "%s %s%%\\n" "$icon" "$vol"
