#!/bin/sh

show_help() {
echo fixnames [OPTIONS...] [FILE...]
echo
echo OPTIONS
echo -i   ignore FILES listed
echo -d   include directories
echo -.   include dot files
echo -h   show this message
echo -?   same as -h
echo
echo FILE
echo if included, only those filenames are fixed
echo
}

OPTIND=1
ignore=0
dot=0
dir=0

while getopts "id.h?" opt; do
    case $opt in
    h|\?) show_help
				  exit 0 ;;
    i)    ignore=1 ;;
    d)    dir=1 ;;
    .)    dot=1 ;;
    esac
done

shift $((OPTIND-1))
[ "${1:-}" = "--" ] && shift


com='ls '

if [ $dot == 1 ]; then
	com+='-A '
fi

list=
OLDIFS=$IFS
IFS=$'\n'

for x in $(eval $com)
do
	if [ -f "$x" ]; then
		list+="$x"
	elif [ $dir == 1 -a -d "$x" ]; then
		list+="$x"
	fi
	list+=$'\n'
done

if [ $ignore == 1 ]; then
	ignList=$(echo $@ | tr ' ' '|')
	list=$(echo -e "$list" | grep -Exv "$ignList")
fi

if [ $ignore == 0 -a $dot == 0 -a $dir == 0 ]; then
	if [ "$@" ]; then
		list=$(echo $@ | tr ' ' '\n')
	fi
fi


for x in $(echo -e "$list")
do
	if [ "$x" ]; then
		fixName=$(echo "$x" | tr -dc "[:alnum:][:blank:]-_")
		fixName=$(echo "$fixName" | tr '[A-Z]' '[a-z]')
		fixName=$(echo "$fixName" | tr '_[:blank:]' '-')
		fixName=$(echo "$fixName" | tr -s '-' '-')
		if [ "$fixName" != "$x" ]; then
			mv -i "$x" "$fixName"
		fi
	fi
done
IFS=$OLDIFS
