#!/bin/sh

PRIM=$(xclip -o -selection primary)
CLIP=$(xclip -o -selection clipboard)

PR=$(echo $PRIM | head -n 1 | cut -c-10)
CL=$(echo $CLIP | head -n 1 | cut -c-10)

RES=$(echo -e "$PR\n$CL" | dmenu -i)

if [ $RES == $PR ]
then
	echo "$PRIM" | xclip -i -selection clipboard
	echo "$PRIM" | xclip -i -selection primary
fi

if [ $RES == $CL ]
then
	echo "$CLIP" | xclip -i -selection clipboard
	echo "$CLIP" | xclip -i -selection primary
fi
