#!/bin/sh

hsetroot -fill "$HOME/.config/wall.png"

### OLD ###
#hsetroot -fill "$HOME/.config/wall.png" -brightness -.12
# hsetroot -screens 3 -fill $HOME/.config/wall.png -brightness -.12

### setwallpaperx ###
# xwallpaper --zoom ~/.config/wall.png
