#!/bin/sh

case $BLOCK_BUTTON in
	1) setsid "$TERMINAL" -e amixer & ;;
	3) amixer sset Master toggle >/dev/null;;
	4) amixer sset Master 5%+ >/dev/null;;
	5) amixer sset Master 5%- >/dev/null;;
esac

[ "$(amixer sget Master | tail -n 1 | awk '{print $6}')" = "[off]" ] && printf "🔇\\n" && exit

vol=$(amixer sget Master | tail -n 1 | awk '{print $4}' | tr -d "[]%")

if [ "$vol" -gt "70" ]
then
	icon="🔊"
elif [ "$vol" -lt "30" ]
then
	icon="🔈"
else
	icon="🔉"
fi

printf "%s %s%%\\n" "$icon" "$vol"
