#!/bin/sh
xrandr --output VGA-1 --off --output LVDS-1 --primary --mode 1280x800 --pos 320x1080 --rotate normal --output HDMI-3 --off --output HDMI-2 --off --output HDMI-1 --mode 1920x1080 --pos 0x0 --rotate normal --output DP-3 --off --output DP-2 --off --output DP-1 --off

setwallpaperx
